apiVersion: v1
kind: Template
labels:
  template: s2i-base-java8-centos7
metadata:
  name: s2i-base-java8-centos7
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: s2i-base-java8-centos7
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: base-java8-centos7:latest
    source:
      git:
        uri: https://github.com/OutThereLabs/s2i-base-java8-centos7.git
    strategy:
      type: Docker
    triggers:
    - github:
        secret: "${GITHUB_WEBHOOK_SECRET}"
      type: GitHub
    - generic:
        secret: "${GENERIC_WEBHOOK_SECRET}"
      type: Generic
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: base-java8-centos7
parameters:
  - name: "GITHUB_WEBHOOK_SECRET"
    displayName: "GitHub Webhook Secret"
    description: "A secret string used to configure the GitHub webhook."
    generate: "expression"
    from: "[a-zA-Z0-9]{40}"
  - name: "GENERIC_WEBHOOK_SECRET"
    displayName: "GitHub Webhook Secret"
    description: "A secret string used to configure the GitHub webhook."
    generate: "expression"
    from: "[a-zA-Z0-9]{40}"
